// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHRY3bfcospqtV2bYexaohI-mmHmk8cI4',
    appId: '1:196412753097:web:7bd6ed50db16be09473918',
    messagingSenderId: '196412753097',
    projectId: 'todo-4469a',
    authDomain: 'todo-4469a.firebaseapp.com',
    storageBucket: 'todo-4469a.appspot.com',
    measurementId: 'G-MP528C9FE4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATFa9FhgnfvsKxrIvC5bPiceeWaCeYKZ8',
    appId: '1:196412753097:android:305035d8fb50138a473918',
    messagingSenderId: '196412753097',
    projectId: 'todo-4469a',
    storageBucket: 'todo-4469a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYud4qvWX2QH6uvGMq_Hv02DZGlNpRlUY',
    appId: '1:196412753097:ios:34d7260ec2809ea0473918',
    messagingSenderId: '196412753097',
    projectId: 'todo-4469a',
    storageBucket: 'todo-4469a.appspot.com',
    iosClientId: '196412753097-4rmiccua71htvr12v37a07pslv7nd74a.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYud4qvWX2QH6uvGMq_Hv02DZGlNpRlUY',
    appId: '1:196412753097:ios:fc532e9c18596219473918',
    messagingSenderId: '196412753097',
    projectId: 'todo-4469a',
    storageBucket: 'todo-4469a.appspot.com',
    iosClientId: '196412753097-lk05np2s102bmhamgbko1kgm7vdiqeau.apps.googleusercontent.com',
    iosBundleId: 'com.example.project.RunnerTests',
  );
}
